[2024-10-04T23:17:26.494+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_mysql.insert_client_task manual__2024-10-04T23:17:19.114757+00:00 [queued]>
[2024-10-04T23:17:26.510+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_mysql.insert_client_task manual__2024-10-04T23:17:19.114757+00:00 [queued]>
[2024-10-04T23:17:26.510+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-04T23:17:26.532+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): insert_client_task> on 2024-10-04 23:17:19.114757+00:00
[2024-10-04T23:17:26.542+0000] {standard_task_runner.py:60} INFO - Started process 206 to run task
[2024-10-04T23:17:26.547+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_mysql', 'insert_client_task', 'manual__2024-10-04T23:17:19.114757+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmpwvkiabtj']
[2024-10-04T23:17:26.549+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask insert_client_task
[2024-10-04T23:17:26.624+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_mysql.insert_client_task manual__2024-10-04T23:17:19.114757+00:00 [running]> on host ffa59a91c4ec
[2024-10-04T23:17:26.763+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_mysql' AIRFLOW_CTX_TASK_ID='insert_client_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:17:19.114757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T23:17:19.114757+00:00'
[2024-10-04T23:17:26.767+0000] {sql.py:276} INFO - Executing: 
        INSERT INTO clients (nom, email) 
        VALUES ('ClientTest', 'client@example.com');
        
[2024-10-04T23:17:26.783+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:17:26.808+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:17:26.832+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO clients (nom, email) 
        VALUES ('ClientTest', 'client@example.com');
        , parameters: None
[2024-10-04T23:17:26.854+0000] {sql.py:459} INFO - Rows affected: 1
[2024-10-04T23:17:26.874+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_table_in_mysql, task_id=insert_client_task, execution_date=20241004T231719, start_date=20241004T231726, end_date=20241004T231726
[2024-10-04T23:17:26.922+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-04T23:17:26.947+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
