[2024-10-04T23:25:13.645+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T23:25:10.616492+00:00 [queued]>
[2024-10-04T23:25:13.656+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T23:25:10.616492+00:00 [queued]>
[2024-10-04T23:25:13.656+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-04T23:25:14.519+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): create_table_task> on 2024-10-04 23:25:10.616492+00:00
[2024-10-04T23:25:15.517+0000] {standard_task_runner.py:60} INFO - Started process 333 to run task
[2024-10-04T23:25:15.526+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_mysql', 'create_table_task', 'manual__2024-10-04T23:25:10.616492+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmpulzgzi8_']
[2024-10-04T23:25:15.530+0000] {standard_task_runner.py:88} INFO - Job 133: Subtask create_table_task
[2024-10-04T23:25:15.721+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T23:25:10.616492+00:00 [running]> on host ffa59a91c4ec
[2024-10-04T23:25:15.880+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_mysql' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:25:10.616492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T23:25:10.616492+00:00'
[2024-10-04T23:25:15.882+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS clients (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        
[2024-10-04T23:25:15.897+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:25:15.912+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:25:16.044+0000] {sql.py:450} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS clients (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        , parameters: None
[2024-10-04T23:25:16.125+0000] {sql.py:459} INFO - Rows affected: 0
[2024-10-04T23:25:16.142+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_table_in_mysql, task_id=create_table_task, execution_date=20241004T232510, start_date=20241004T232513, end_date=20241004T232516
[2024-10-04T23:25:16.184+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-04T23:25:16.206+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
