[2024-10-04T23:22:28.971+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_mysql.insert_client_task manual__2024-10-04T23:22:20.901133+00:00 [queued]>
[2024-10-04T23:22:28.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_mysql.insert_client_task manual__2024-10-04T23:22:20.901133+00:00 [queued]>
[2024-10-04T23:22:28.983+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-04T23:22:29.004+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): insert_client_task> on 2024-10-04 23:22:20.901133+00:00
[2024-10-04T23:22:29.013+0000] {standard_task_runner.py:60} INFO - Started process 288 to run task
[2024-10-04T23:22:29.018+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_mysql', 'insert_client_task', 'manual__2024-10-04T23:22:20.901133+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmp2pic9bd0']
[2024-10-04T23:22:29.022+0000] {standard_task_runner.py:88} INFO - Job 132: Subtask insert_client_task
[2024-10-04T23:22:29.091+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_mysql.insert_client_task manual__2024-10-04T23:22:20.901133+00:00 [running]> on host ffa59a91c4ec
[2024-10-04T23:22:29.198+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_mysql' AIRFLOW_CTX_TASK_ID='insert_client_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:22:20.901133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T23:22:20.901133+00:00'
[2024-10-04T23:22:29.200+0000] {sql.py:276} INFO - Executing: 
        INSERT INTO clients (nom, email) 
        VALUES ('ClientTest', 'client@example.com');
        
[2024-10-04T23:22:29.213+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:22:29.227+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:22:29.254+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO clients (nom, email) 
        VALUES ('ClientTest', 'client@example.com');
        , parameters: None
[2024-10-04T23:22:29.266+0000] {sql.py:459} INFO - Rows affected: 1
[2024-10-04T23:22:29.283+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_table_in_mysql, task_id=insert_client_task, execution_date=20241004T232220, start_date=20241004T232228, end_date=20241004T232229
[2024-10-04T23:22:29.312+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-04T23:22:29.334+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
